# Generated by Django 5.0.6 on 2024-07-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IP_log', '0003_userrole_name_alter_userrole_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
