# Generated by Django 5.0.6 on 2024-07-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IP_log', '0007_alter_customuser_managers_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('gold', 'GOLD'), ('silver', 'SILVER'), ('bronze', 'BRONZE')], default='bronze', max_length=10),
        ),
    ]
