# Generated by Django 5.0.6 on 2024-07-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IP_log', '0010_profile_last_access_time_alter_profile_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_access_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('gold', 'GOLD'), ('silver', 'SILVER'), ('bronze', 'BRONZE')], max_length=10),
        ),
    ]
